create table public.productos (
id bigint generated by default as identity primary key,
codigo text not null,nombre text not null,categoria text not null,estado text,
cantidad numeric not null default 0,unidad text,ingreso date,vencimiento date,
ubicacion text,riesgo text,envase text,observaciones text,alumno text,
created_at timestamptz default now());
create index productos_vencimiento_idx on public.productos(vencimiento);
create index productos_codigo_idx on public.productos(codigo);